org.gradle.jvmargs=-Xmx1g -XX:MaxMetaspaceSize=512m

javaVersion=21
versionsVersion=0.54.0
openRewriteVersion=7.37.0
openRewriteRecipeBomVersion=3.35.0
openRewriteSpringVersion=6.35.0

# https://mvnrepository.com/artifact/org.springframework.boot/spring-boot
springBootVersion=4.1.0
springVersion=7.0.8
# https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-logging
logbackVersion=1.5.34
slf4jVersion=2.0.17
# https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-mail
jakartaMailVersion=2.1.5
# https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-security
springSecurityVersion=7.1.0

# https://mvnrepository.com/artifact/org.springframework.data/spring-data-mongodb
springDataMongodbVersion=5.1.0
springDataVersion=4.1.0
mongodbDriverVersion=5.8.0

# https://mvnrepository.com/artifact/org.bouncycastle/bcprov-jdk18on
bouncyCastleVersion=1.85
commonsLang3Version=3.20.0
freemarkerVersion=2.3.34
guavaVersion=33.6.0-jre
jacksonDatabindVersion=3.2.1
jakartaAnnotationVersion=3.0.0
jschVersion=0.1.55

# Testing
junit6Version=6.1.2
mockitoVersion=5.23.0
# https://mvnrepository.com/artifact/de.flapdoodle.embed/de.flapdoodle.embed.mongo
flapdoodleVersion=4.33.0
